core/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from core.views import DashboardView, IndexView, OpenTicketView, ClosedTicketView, UsersView, ImportDataView, \
    CustomPasswordChangeView, ImportUsersView, ImportDataHistoryView, ImportUsersHistoryView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('dashboard/open-ticket/<str:service_id>', OpenTicketView.as_view(), name='open-ticket'),
    path('dashboard/closed-ticket/<str:service_id>', ClosedTicketView.as_view(), name='closed-ticket'),
    path('dashboard/users', UsersView.as_view(), name='admin-users'),
    path('dashboard/import-data', ImportDataView.as_view(), name='admin-import'),
    path('dashboard/import-users', ImportUsersView.as_view(), name='admin-import-users'),
    path('dashboard/import-data-history', ImportDataHistoryView.as_view(), name='admin-import-data-history'),
    path('dashboard/import-users-history', ImportUsersHistoryView.as_view(), name='admin-import-users-history'),
    path('dashboard/change-password', CustomPasswordChangeView.as_view(), name='change-password'),
    path('login', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

indosat_b2b/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models

# Create your models here.

class MyUserManager(UserManager):
    def get_by_natural_key(self, username):
        return self.get(username__iexact=username)

class User(AbstractUser):
    # username_validator = UnicodeUsernameValidator()
    # email = models.EmailField('email address', blank=True, unique=True)
    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = []
    level = models.IntegerField(null=True)
    objects = MyUserManager()
    name = models.CharField(max_length=256)

    def get_salespeople(self):
        return getattr(self, f'subordinates_{self.level}').all() if self.level > 1 else []

    level_2_superior = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subordinates_2', null=True)
    level_3_superior = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subordinates_3', null=True)
    level_4_superior = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subordinates_4', null=True)
    level_5_superior = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subordinates_5', null=True)
    level_6_superior = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subordinates_6', null=True)

def file_directory_path(instance, filename):
    return f'uploads/{instance.payload_name}/{instance.upload_time.strftime("%Y%m%d%H%M%S")}/{filename}'

class History(models.Model):

    upload_time = models.DateTimeField()
    payload_name = models.CharField(max_length=128)
    uploader_nik = models.CharField(max_length=128)
    file = models.FileField(upload_to=file_directory_path)

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

core/views.py
from datetime import datetime, timedelta

import pandas as pd
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.exceptions import SuspiciousOperation
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView

from core.DataManager import DataManager
from core.UserManager import UserManager
from core.helpers import filter_ticket_request, get_ticket_meta, query_request, is_expired_soon, as_rupiah, \
    process_user_data, filter_results_by_user
from core.history_manager import HistoryManager
from core.models import User

data_manager = DataManager()
user_manager = UserManager()

class IndexView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('core:dashboard'))
        else:
            return redirect(reverse('core:login'))

class DashboardView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        if not data_manager._initialized:
            return render(request, template_name='core/dashboard.html')

        table_headings = data_manager.links_df.columns.tolist()

        queried = query_request(request, data_manager.links_df)

        try:
            req_page = request.GET.get('page', 1) or 1
            page_num = int(req_page)
        except (ValueError, TypeError):
            raise SuspiciousOperation('Page number is invalid')

        queried = filter_results_by_user(request, queried)

        p = Paginator(queried.fillna('-').values.tolist(), 50)

        data = p.page(page_num)

        total_mrc = as_rupiah(queried.MRC_IDR.sum())

        links_expired_soon = queried if queried.empty else queried[queried['TERMINATION_DATE'].apply(is_expired_soon)]
        mrc_expired_soon = as_rupiah(links_expired_soon['MRC_IDR'].sum())
        num_expired_soon = len(links_expired_soon)

        service_id_index = table_headings.index('SERVICE_ID')
        open_ticket_index = table_headings.index('OPEN_TICKET')
        closed_ticket_index = table_headings.index('CLOSED_TICKET')

        dtypes = [(col, data_manager.links_df[col].dtype.name) for col in data_manager.links_df.columns]
        searchable_columns = [i[0] for i in dtypes if i[1] == 'object']

        context = dict(
            table_headings=table_headings,
            searchable_columns=searchable_columns,
            data=data,
            page_range=range(1, p.num_pages + 1),
            current_page=page_num,
            paginator=p,
            total_mrc=total_mrc,
            mrc_expired_soon=mrc_expired_soon,
            num_expired_soon=num_expired_soon,
            service_id_index=service_id_index,
            open_ticket_index=open_ticket_index,
            closed_ticket_index=closed_ticket_index,
            query=request.GET.get('query'),
            filter_by=request.GET.get('by'),
        )

        return render(request, 'core/dashboard.html', context)


class ClosedTicketView(LoginRequiredMixin, View):

    def get(self, request, *args, service_id=None, **kwargs):
        if not data_manager._initialized:
            return render(request, template_name='core/closed_ticket.html')
        queried = filter_ticket_request(request, data_manager.closed_tickets_df, service_id)
        metadata = get_ticket_meta(data_manager.links_df, service_id)

        mttr = queried.HANDLING_TIME_HOURS.mean() or 'N/A'
        average_pending_time = queried.PENDING_TIME_HOURS.mean() or 'N/A'

        try:
            most_problem_resolved = queried['PROBLEM_TIER 1'].mode().iloc[0]
        except IndexError:
            most_problem_resolved = 'N/A'

        dtypes = [(col, data_manager.closed_tickets_df[col].dtype.name) for col in data_manager.closed_tickets_df.columns]
        searchable_columns = [i[0] for i in dtypes if i[1] == 'object']

        context = dict(
            data=queried.fillna('-').values.tolist(),
            table_headings=queried.columns.tolist(),
            searchable_columns=searchable_columns,
            mttr=mttr,
            average_pending_time=average_pending_time,
            most_problem_resolved=most_problem_resolved,
            metadata=metadata,
        )



        return render(request, template_name='core/closed_ticket.html', context=context)


class OpenTicketView(LoginRequiredMixin, View):

    def get(self, request, *args, service_id=None, **kwargs):
        if not data_manager._initialized:
            return render(request, template_name='core/open_ticket.html')

        queried = filter_ticket_request(request, data_manager.open_tickets_df, service_id)
        metadata = get_ticket_meta(data_manager.links_df, service_id)

        buffer = timedelta(days=3)

        average_sr_duration = queried.SR_DURATION_HOURS.mean()
        num_late = len(queried[queried.TICKET_DUE_DATE.apply(lambda x: x < datetime.today())])
        num_expired_soon = len(queried[queried.TICKET_DUE_DATE.apply(lambda x: x - datetime.today() < buffer)])  - num_late

        dtypes = [(col, data_manager.open_tickets_df[col].dtype.name) for col in data_manager.open_tickets_df.columns]
        searchable_columns = [i[0] for i in dtypes if i[1] == 'object']



        context = dict(
            data=queried.fillna('-').values.tolist(),
            searchable_columns=searchable_columns,
            table_headings=queried.columns.tolist(),
            average_sr_duration=average_sr_duration,
            num_late=num_late,
            num_expired_soon=num_expired_soon,
            metadata=metadata,
        )



        return render(request, template_name='core/open_ticket.html', context=context)

class UsersView(View):

    @method_decorator(staff_member_required(login_url=settings.LOGIN_URL))
    def get(self, request, *args, **kwargs):
        context = dict(
            data=process_user_data(User.objects.all()),
            table_headings=['NIK', 'Name', 'Position', 'AVP', 'VP', 'SVP', 'Last Login', 'Is Staff'],
            searchable_columns=['NIK', 'Name', 'Position', 'AVP', 'VP', 'SVP', 'Is Staff'],
        )

        return render(request, template_name='core/users.html', context=context)


class ImportDataView(View):

    def get(self, request, *args, **kwargs):
        return render(request, template_name='core/import_data.html')

    def post(self, request, *args, **kwargs):
        try:
            f = request.FILES['file']
        except KeyError:
            messages.error(request, 'You did not select a file. Please try again.')
            return render(request, template_name='core/import_data.html')

        now = datetime.now()
        dfs = pd.read_excel(f, sheet_name=None)

        data_manager.load_data(dfs)
        HistoryManager.create_history('links_data', request.user.username, f, now)

        messages.success(self.request, 'Data has been successfully uploaded. Click the site icon on the top left to view the newly uploaded data.')
        return render(request, template_name='core/import_data.html')


class ImportDataHistoryView(View):

    def get(self, request, *args, **kwargs):

        data = HistoryManager.get_data_upload_history()

        return render(request, template_name='core/import_data_history.html', context=dict(
            table_headings=['Uploader NIK', 'Upload time', 'File Path in Server'],
            data=data,
        ))


class ImportUsersView(View):

    def get(self, request, *args, **kwargs):
        return render(request, template_name='core/import_users.html')

    def post(self, request, *args, **kwargs):
        try:
            f = request.FILES['file']
        except KeyError:
            messages.error(request, 'You did not select a file. Please try again.')
            return render(request, template_name='core/import_data.html')

        dfs = pd.read_excel(f, sheet_name=None)

        user_manager.load_users(dfs)

        now = datetime.now()

        HistoryManager.create_history('user', request.user.username, f, now)

        messages.success(self.request,
                         'Users have been successfully imported. Go to Admin > Users to view updated users.')
        return render(request, template_name='core/import_users.html')


class ImportUsersHistoryView(View):

    def get(self, request, *args, **kwargs):
        data = HistoryManager.get_user_upload_history()

        return render(request, template_name='core/import_user_history.html', context=dict(
            table_headings=['Uploader NIK', 'Upload time', 'File Path in Server'],
            data=data,
        ))


class SettingsView(View):

    def get(self, request, *args):
        pass

    def post(self, request, *args):
        pass

class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('core:change-password')

    def form_valid(self, form):
        messages.success(self.request, 'Your password has been changed.')
        return super().form_valid(form)

core/templates/core/__core_base.html
{% extends '__base.html' %}
{% load static %}

{% block title %}
    {{ app_name }} | Home
{% endblock %}

{% block body %}
    {% block header %}
        {% include 'core/__header.html' %}
    {% endblock %}
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

core/templates/core/__dashboard_base.html
{% extends 'core/__core_base.html' %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var filter_by="{{ filter_by }}";
    </script>
{% endblock %}

{% block content %}
    <div class="ui container">
        {% block content_header %}

        {% endblock %}
        {% block metadata %}

        {% endblock %}
        <div class="metrics">
            {% block metrics %}

            {% endblock %}
        </div>


        {% block search_filter %}

        {% endblock %}
        {% block table %}
            {% include 'core/_table.html' with table_headings=table_headings data=data %}
        {% endblock %}
    </div>
{% endblock %}

core/templates/core/__header.html
{% load static %}
<header>
    <div class="ui menu">
        <div class="ui item">
            <a href="/" class="ui tiny image">
                <img src="{% static 'images/logo.png' %}" alt="">
            </a>
        </div>
        <div class="right menu">
            <a href="{{ sales_dashboard_url }}" class="item">Sales Dashboard</a>
            {% if request.user.is_staff %}
                <div class="ui dropdown item">
                    <span class="text">Admin</span>
                    <div class="menu">
                        <a href="{% url 'core:admin-users' %}" class="item">Users</a>
                        <a href="{% url 'core:admin-import' %}" class="item">Import Data</a>
                        <a href="{% url 'core:admin-import-users' %}" class="item">Import Users</a>
                        <a href="{% url 'core:admin-import-users-history' %}" class="item">Users Import History</a>
                        <a href="{% url 'core:admin-import-data-history' %}" class="item">Data Import History</a>
                    </div>
                </div>

            {% endif %}
            <div class="item header-email">{{ request.user.username }}</div>
            <a href="{% url 'core:change-password' %}" class="item">Change password</a>
            <a href="{% url 'core:logout' %}" class="item">Logout</a>
        </div>
    </div>
</header>

core/templates/core/__messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="ui positive message">
                    <i class="close icon"></i>
                    <div class="header">
                        Success!
                    </div>
                    {{ message }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                <div class="ui warning message">
                    <i class="close icon"></i>
                    <div class="header">
                        Warning!
                    </div>
                    {{ message }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="ui negative message">
                    <i class="close icon"></i>
                    <div class="header">
                        Error!
                    </div>
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

core/templates/core/__ticket_base.html
{% extends 'core/__core_base.html' %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var filter_by="{{ filter_by }}";
    </script>
{% endblock %}

{% block content %}
    <div class="ui container">
        {% block content_header %}

        {% endblock %}
        {% block metadata %}

        {% endblock %}
        {% block metrics %}

        {% endblock %}

        {% block search_filter %}

            {% include 'core/_search_filter_section.html' with table_headings=table_headings %}

        {% endblock %}
        {% block table %}
            {% include 'core/_table.html' with table_headings=table_headings data=data %}
        {% endblock %}
    </div>
{% endblock %}

core/templates/core/_metadata.html
<div class="metadata">
    <table class="ui very basic collapsing table">
        <tbody>
        {% for row in data %}
            <tr>
            {% for cell in row %}
                <td>{{ cell }}</td>
            {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

core/templates/core/_metric.html
<div class="ui card">
    <div class="content">
        <h4 class="center aligned header">
            {{ title }}
        </h4>
    </div>
    <div class="center aligned content">
        {{ content }}
    </div>
</div>

core/templates/core/_search_filter_section.html
<div class="search-filter">
    <form action="" class="ui form" method="get">
        <div class="field">
            <input type="text" value="{% if query %}{{ query }}{% endif %}" name="query" placeholder="Search">
        </div>

        <div class="field">
            <select class="ui dropdown" name="by">
                <option value="">By</option>
                {% for column in searchable_columns %}
                    <option value="{{ column }}">{{ column }}</option>
                {% endfor %}
            </select>
        </div>
        {#        Add sort functionality #}
        <button class="ui red button" type="submit">Search</button>
    </form>
</div>

core/templates/core/closed_ticket.html
{% extends 'core/__dashboard_base.html' %}

{% block content_header %}
    <h2 class="ui header">Closed Tickets</h2>
{% endblock %}

{% block metadata %}
    {% include 'core/_metadata.html' with data=metadata %}
{% endblock %}

{% block metrics %}
    <div class="ui three stackable cards">
        {% include 'core/_metric.html' with title='Mean Time to Repair (hours)' content=mttr %}
        {% include 'core/_metric.html' with title='Average Pending Time (hours)' content=average_pending_time %}
        {% include 'core/_metric.html' with title='Most Problem Resolved' content=most_problem_resolved %}
    </div>
{% endblock %}

core/templates/core/import.html
{% extends 'core/__core_base.html' %}
{% block content %}
    <div class="ui container">
        <h2 class="ui header">Import data</h2>
        {% include 'core/__messages.html' %}
        <form action="" class="ui form" method="post" enctype="multipart/form-data">
            <div class="field input-container">
                <div class="ui red large button import-button">
                    Select File
                    <input type="file" name="file" class="file-input-hidden">
                </div>
            </div>
            {% csrf_token %}
            <button class="ui medium button" type="submit">Upload</button>
        </form>
    </div>
{% endblock %}

core/templates/core/import_data.html
{% extends 'core/__core_base.html' %}
{% block content %}
    <div class="ui container">
        <h2 class="ui header">Import data</h2>
        {% include 'core/__messages.html' %}
        <form action="" class="ui form" method="post" enctype="multipart/form-data">
            <div class="field input-container">
                <div class="ui red large button import-button">
                    Select File
                    <input type="file" name="file" class="file-input-hidden">
                </div>
            </div>
            {% csrf_token %}
            <button class="ui medium button" type="submit">Upload</button>
        </form>
    </div>
{% endblock %}

core/templates/core/import_data_history.html
{% extends 'core/__dashboard_base.html' %}

{% block content_header %}
    <h2 class="ui header">Data Import History</h2>
{% endblock %}

core/templates/core/import_users.html
{% extends 'core/__core_base.html' %}
{% block content %}
    <div class="ui container">
        <h2 class="ui header">Import Users</h2>
        {% include 'core/__messages.html' %}
        <form action="" class="ui form" method="post" enctype="multipart/form-data">
            <div class="field input-container">
                <div class="ui red large button import-button">
                    Select File
                    <input type="file" name="file" class="file-input-hidden">
                </div>
            </div>
            {% csrf_token %}
            <button class="ui medium button" type="submit">Upload</button>
        </form>
    </div>
{% endblock %}

core/templates/core/open_ticket.html
{% extends 'core/__dashboard_base.html' %}

{% block content_header %}
    <h2 class="ui header">Open Tickets</h2>
{% endblock %}

{% block metadata %}
    {% include 'core/_metadata.html' with data=metadata %}
{% endblock %}

{% block metrics %}
    <div class="ui three stackable cards">
        {% include 'core/_metric.html' with title='Average SR duration (hours)' content=average_sr_duration %}
        {% include 'core/_metric.html' with title='Ticket Passed Due Date (hours)' content=num_late %}
        {% include 'core/_metric.html' with title='Ticket Exired Soon (Based on Due Date)' content=num_expired_soon %}
    </div>
{% endblock %}